num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
num3 = input("Enter third number: ")
sum = int(num1) + int (num2) + int(num3)
print(sum)
sum2 = int(num1) - int(num2)
print(sum2)
sum3 = int(num3) * int(num1)
print(sum3)
sum4 = sum / int(num3)
print(sum4) 